services:
  fedml-server:
    build: .
    container_name: fedml-server
    command: >
      python -u src/main.py
      --cf config/fedml_config.yaml
      --rank 0
      --device_id 0
    networks:
      - swarm-net

  fedml-client1:
    build: .
    container_name: fedml-client1
    command: >
      python -u src/main.py
      --cf config/fedml_config.yaml
      --rank 1
      --device_id 1
    depends_on:
      - fedml-server
    networks:
      - swarm-net

  fedml-client2:
    build: .
    container_name: fedml-client2
    command: >
      python -u src/main.py
      --cf config/fedml_config.yaml
      --rank 2
      --device_id 2
    depends_on:
      - fedml-server
    networks:
      - swarm-net

networks:
  swarm-net:
    driver: bridge
