services:
  node1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node1
    environment:
      - ROLE=node
      - NODE_ID=node1
      - PEERS=node2:5555,node3:5555
      - PYTHONUNBUFFERED=1
    networks:
      - swarm-net
    ports:
      - "5001:5555"

  node2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node2
    environment:
      - ROLE=node
      - NODE_ID=node2
      - PEERS=node1:5555,node3:5555
      - PYTHONUNBUFFERED=1
    networks:
      - swarm-net
    ports:
      - "5002:5555"

  node3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node3
    environment:
      - ROLE=node
      - NODE_ID=node3
      - PEERS=node1:5555,node2:5555
      - PYTHONUNBUFFERED=1
    networks:
      - swarm-net
    ports:
      - "5003:5555"

networks:
  swarm-net:
    driver: bridge
