services:
  node1:
    build: .
    environment:
      - NODE_ID=node1
      - PEERS=node2:5555,node3:5555
      - DATA_PATH=/app/data/df_filtered_cnn.pkl
    volumes:
      - ./data:/app/data:ro
    ports:
      - "5555:5555"
    networks:
      - swarm-network

  node2:
    build: .
    environment:
      - NODE_ID=node2
      - PEERS=node1:5555,node3:5555
      - DATA_PATH=/app/data/df_filtered_cnn.pkl
    volumes:
      - ./data:/app/data:ro
    ports:
      - "5556:5555"
    networks:
      - swarm-network

  node3:
    build: .
    environment:
      - NODE_ID=node3
      - PEERS=node1:5555,node2:5555
      - DATA_PATH=/app/data/df_filtered_cnn.pkl
    volumes:
      - ./data:/app/data:ro
    ports:
      - "5557:5555"
    networks:
      - swarm-network

networks:
  swarm-network:
    driver: bridge
