services:
  node1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node1
    environment:
      - ROLE=node
      - NODE_ID=node1
      - PEERS=http://node2:5000,http://node3:5000
    ports:
      - "5001:5000"
    networks:
      - swarm-net

  node2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node2
    environment:
      - ROLE=node
      - NODE_ID=node2
      - PEERS=http://node1:5000,http://node3:5000
    ports:
      - "5002:5000"
    networks:
      - swarm-net

  node3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node3
    environment:
      - ROLE=node
      - NODE_ID=node3
      - PEERS=http://node1:5000,http://node2:5000
    ports:
      - "5003:5000"
    networks:
      - swarm-net

networks:
  swarm-net:
    driver: bridge
