version: '3.8'
services:
  aggregator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aggregator
    environment:
      - ROLE=aggregator
    ports:
      - "5001:5000"
    networks:
      - swarm-net

  node1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node1
    environment:
      - ROLE=node
      - NODE_ID=node1
      - AGGREGATOR_URL=http://aggregator:5000
    networks:
      - swarm-net

  node2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node2
    environment:
      - ROLE=node
      - NODE_ID=node2
      - AGGREGATOR_URL=http://aggregator:5000
    networks:
      - swarm-net

  node3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node3
    environment:
      - ROLE=node
      - NODE_ID=node3
      - AGGREGATOR_URL=http://aggregator:5000
    networks:
      - swarm-net

networks:
  swarm-net:
    driver: bridge
