common_args:
  training_type: "cross_silo"
  scenario: "horizontal"
  random_seed: 0

data_args:
  dataset: "mobifall"
  data_cache_dir: "./data"
  partition_method: "hetero"
  partition_alpha: 0.5

model_args:
  model: "cnn"
  # global_model_file_path: "./model_file_cache/global_model.pt"

train_args:
  federated_optimizer: "FedAvg"
  comm_round: 10
  client_num_in_total: 3
  client_num_per_round: 1
  epochs: 5
  batch_size: 32
  learning_rate: 0.01

comm_args:
  backend: "MQTT_S3"
  mqtt_config_path: "config/mqtt_config.yaml"

device_args:
  using_gpu: false
